/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DeskIndexRouteImport } from './routes/desk/index'
import { Route as DeskContractorsRouteImport } from './routes/desk/contractors'
import { Route as DeskNewTenderRouteImport } from './routes/desk/new-tender'
import { Route as DeskSettingsRouteImport } from './routes/desk/settings'
import { Route as DeskTemplatesRouteImport } from './routes/desk/templates'
import { Route as DeskTendersRouteImport } from './routes/desk/tenders'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DeskInboxIdRouteImport } from './routes/desk/inbox.$id'
import { Route as DeskTemplatesIdRouteImport } from './routes/desk/templates.$id'
import { Route as DeskTendersIdRouteImport } from './routes/desk/tenders.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskIndexRoute = DeskIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeskRoute,
} as any)
const DeskContractorsRoute = DeskContractorsRouteImport.update({
  id: '/contractors',
  path: '/contractors',
  getParentRoute: () => DeskRoute,
} as any)
const DeskNewTenderRoute = DeskNewTenderRouteImport.update({
  id: '/new-tender',
  path: '/new-tender',
  getParentRoute: () => DeskRoute,
} as any)
const DeskSettingsRoute = DeskSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DeskRoute,
} as any)
const DeskTemplatesRoute = DeskTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => DeskRoute,
} as any)
const DeskTendersRoute = DeskTendersRouteImport.update({
  id: '/tenders',
  path: '/tenders',
  getParentRoute: () => DeskRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskInboxIdRoute = DeskInboxIdRouteImport.update({
  id: '/inbox/$id',
  path: '/inbox/$id',
  getParentRoute: () => DeskRoute,
} as any)
const DeskTemplatesIdRoute = DeskTemplatesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DeskTemplatesRoute,
} as any)
const DeskTendersIdRoute = DeskTendersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DeskTendersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/desk': typeof DeskRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/desk/contractors': typeof DeskContractorsRoute
  '/desk/new-tender': typeof DeskNewTenderRoute
  '/desk/settings': typeof DeskSettingsRoute
  '/desk/templates': typeof DeskTemplatesRouteWithChildren
  '/desk/tenders': typeof DeskTendersRouteWithChildren
  '/desk/': typeof DeskIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/desk/inbox/$id': typeof DeskInboxIdRoute
  '/desk/templates/$id': typeof DeskTemplatesIdRoute
  '/desk/tenders/$id': typeof DeskTendersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/desk/contractors': typeof DeskContractorsRoute
  '/desk/new-tender': typeof DeskNewTenderRoute
  '/desk/settings': typeof DeskSettingsRoute
  '/desk/templates': typeof DeskTemplatesRouteWithChildren
  '/desk/tenders': typeof DeskTendersRouteWithChildren
  '/desk': typeof DeskIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/desk/inbox/$id': typeof DeskInboxIdRoute
  '/desk/templates/$id': typeof DeskTemplatesIdRoute
  '/desk/tenders/$id': typeof DeskTendersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/desk': typeof DeskRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/desk/contractors': typeof DeskContractorsRoute
  '/desk/new-tender': typeof DeskNewTenderRoute
  '/desk/settings': typeof DeskSettingsRoute
  '/desk/templates': typeof DeskTemplatesRouteWithChildren
  '/desk/tenders': typeof DeskTendersRouteWithChildren
  '/desk/': typeof DeskIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/desk/inbox/$id': typeof DeskInboxIdRoute
  '/desk/templates/$id': typeof DeskTemplatesIdRoute
  '/desk/tenders/$id': typeof DeskTendersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/desk'
    | '/login'
    | '/onboarding'
    | '/desk/contractors'
    | '/desk/new-tender'
    | '/desk/settings'
    | '/desk/templates'
    | '/desk/tenders'
    | '/desk/'
    | '/api/auth/$'
    | '/desk/inbox/$id'
    | '/desk/templates/$id'
    | '/desk/tenders/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/desk/contractors'
    | '/desk/new-tender'
    | '/desk/settings'
    | '/desk/templates'
    | '/desk/tenders'
    | '/desk'
    | '/api/auth/$'
    | '/desk/inbox/$id'
    | '/desk/templates/$id'
    | '/desk/tenders/$id'
  id:
    | '__root__'
    | '/'
    | '/desk'
    | '/login'
    | '/onboarding'
    | '/desk/contractors'
    | '/desk/new-tender'
    | '/desk/settings'
    | '/desk/templates'
    | '/desk/tenders'
    | '/desk/'
    | '/api/auth/$'
    | '/desk/inbox/$id'
    | '/desk/templates/$id'
    | '/desk/tenders/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeskRoute: typeof DeskRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk/': {
      id: '/desk/'
      path: '/'
      fullPath: '/desk/'
      preLoaderRoute: typeof DeskIndexRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/contractors': {
      id: '/desk/contractors'
      path: '/contractors'
      fullPath: '/desk/contractors'
      preLoaderRoute: typeof DeskContractorsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/new-tender': {
      id: '/desk/new-tender'
      path: '/new-tender'
      fullPath: '/desk/new-tender'
      preLoaderRoute: typeof DeskNewTenderRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/settings': {
      id: '/desk/settings'
      path: '/settings'
      fullPath: '/desk/settings'
      preLoaderRoute: typeof DeskSettingsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/templates': {
      id: '/desk/templates'
      path: '/templates'
      fullPath: '/desk/templates'
      preLoaderRoute: typeof DeskTemplatesRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/tenders': {
      id: '/desk/tenders'
      path: '/tenders'
      fullPath: '/desk/tenders'
      preLoaderRoute: typeof DeskTendersRouteImport
      parentRoute: typeof DeskRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk/inbox/$id': {
      id: '/desk/inbox/$id'
      path: '/inbox/$id'
      fullPath: '/desk/inbox/$id'
      preLoaderRoute: typeof DeskInboxIdRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/templates/$id': {
      id: '/desk/templates/$id'
      path: '/$id'
      fullPath: '/desk/templates/$id'
      preLoaderRoute: typeof DeskTemplatesIdRouteImport
      parentRoute: typeof DeskTemplatesRoute
    }
    '/desk/tenders/$id': {
      id: '/desk/tenders/$id'
      path: '/$id'
      fullPath: '/desk/tenders/$id'
      preLoaderRoute: typeof DeskTendersIdRouteImport
      parentRoute: typeof DeskTendersRoute
    }
  }
}

interface DeskTemplatesRouteChildren {
  DeskTemplatesIdRoute: typeof DeskTemplatesIdRoute
}

const DeskTemplatesRouteChildren: DeskTemplatesRouteChildren = {
  DeskTemplatesIdRoute: DeskTemplatesIdRoute,
}

const DeskTemplatesRouteWithChildren = DeskTemplatesRoute._addFileChildren(
  DeskTemplatesRouteChildren,
)

interface DeskTendersRouteChildren {
  DeskTendersIdRoute: typeof DeskTendersIdRoute
}

const DeskTendersRouteChildren: DeskTendersRouteChildren = {
  DeskTendersIdRoute: DeskTendersIdRoute,
}

const DeskTendersRouteWithChildren = DeskTendersRoute._addFileChildren(
  DeskTendersRouteChildren,
)

interface DeskRouteChildren {
  DeskContractorsRoute: typeof DeskContractorsRoute
  DeskNewTenderRoute: typeof DeskNewTenderRoute
  DeskSettingsRoute: typeof DeskSettingsRoute
  DeskTemplatesRoute: typeof DeskTemplatesRouteWithChildren
  DeskTendersRoute: typeof DeskTendersRouteWithChildren
  DeskIndexRoute: typeof DeskIndexRoute
  DeskInboxIdRoute: typeof DeskInboxIdRoute
}

const DeskRouteChildren: DeskRouteChildren = {
  DeskContractorsRoute: DeskContractorsRoute,
  DeskNewTenderRoute: DeskNewTenderRoute,
  DeskSettingsRoute: DeskSettingsRoute,
  DeskTemplatesRoute: DeskTemplatesRouteWithChildren,
  DeskTendersRoute: DeskTendersRouteWithChildren,
  DeskIndexRoute: DeskIndexRoute,
  DeskInboxIdRoute: DeskInboxIdRoute,
}

const DeskRouteWithChildren = DeskRoute._addFileChildren(DeskRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeskRoute: DeskRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
